NUM_ACTIONS = 3
BUCKET_NUM = 5

FOLD = 0
CALL = 1
RAISE = 2

PREFLOP = 0
FLOP = 1
TURN = 2
RIVER = 3

NUM_ROUND = 4
SMALL_BLIND = 20
NUM_PLAYER = 2
NUM_SUIT = 4
NUM_RANK = 13
NUM_HOLE_CARDS = 2
NUM_COMMUNITY_CARD_DRAWN_PREFLOP = 0
NUM_COMMUNITY_CARD_DRAWN_FLOP = 3
NUM_COMMUNITY_CARD_DRAWN_TURN_AND_RIVER = 1
MAX_RAISE_PREFLOP = 3
MAX_RAISE_AFTER_FLOP = 4
MAX_RAISE_PER_PLAYER = 4
FIRST_PLAYER_INDEX = 0
BETTING_TYPE = 1
RAISE_AMT_BEFORE_TURN = 20
RAISE_AMT_AFTER_TURN = 40
