import copy
import pprint
from enum import Enum, unique

from pypokerengine.utils.card_utils import (estimate_hole_card_win_rate,
                                            gen_cards)


""" Example round state generated by emulator

        {'street': 'river', 'pot': {'main': {'amount': 400}, 'side': []},
         'community_card': ['DT', 'C2', 'ST', 'DA', 'HT'],
         'dealer_btn': 1, 'next_player': 1, 'small_blind_pos': 0, 'big_blind_pos': 1, 'round_count': 10,
         'small_blind_amount': 10,
         'seats': [{'name': 'f1', 'uuid': 'zdmxlmfwytkigodciubiow', 'stack': 10200, 'state': 'participating'},
                   {'name': 'FT2', 'uuid': 'lnjvmobrxhizukrppiqbda', 'stack': 9400, 'state': 'participating'}],
         'action_histories': {
             'preflop': [{'action': 'SMALLBLIND', 'amount': 10, 'add_amount': 10, 'uuid': 'zdmxlmfwytkigodciubiow'},
                         {'action': 'BIGBLIND', 'amount': 20, 'add_amount': 10, 'uuid': 'lnjvmobrxhizukrppiqbda'},
                         {'action': 'RAISE', 'amount': 40, 'paid': 30, 'add_amount': 20,
                          'uuid': 'zdmxlmfwytkigodciubiow'},
                         {'action': 'RAISE', 'amount': 60, 'paid': 40, 'add_amount': 20,
                          'uuid': 'lnjvmobrxhizukrppiqbda'},
                         {'action': 'RAISE', 'amount': 80, 'paid': 40, 'add_amount': 20,
                          'uuid': 'zdmxlmfwytkigodciubiow'},
                         {'action': 'CALL', 'amount': 80, 'paid': 20, 'uuid': 'lnjvmobrxhizukrppiqbda'}],
             'flop': [{'action': 'RAISE', 'amount': 20, 'paid': 20, 'add_amount': 20, 'uuid': 'zdmxlmfwytkigodciubiow'},
                      {'action': 'RAISE', 'amount': 40, 'paid': 40, 'add_amount': 20, 'uuid': 'lnjvmobrxhizukrppiqbda'},
                      {'action': 'RAISE', 'amount': 60, 'paid': 40, 'add_amount': 20, 'uuid': 'zdmxlmfwytkigodciubiow'},
                      {'action': 'RAISE', 'amount': 80, 'paid': 40, 'add_amount': 20, 'uuid': 'lnjvmobrxhizukrppiqbda'},
                      {'action': 'CALL', 'amount': 80, 'paid': 20, 'uuid': 'zdmxlmfwytkigodciubiow'}],
             'turn': [{'action': 'CALL', 'amount': 0, 'paid': 0, 'uuid': 'zdmxlmfwytkigodciubiow'},
                      {'action': 'RAISE', 'amount': 40, 'paid': 40, 'add_amount': 40, 'uuid': 'lnjvmobrxhizukrppiqbda'},
                      {'action': 'CALL', 'amount': 40, 'paid': 40, 'uuid': 'zdmxlmfwytkigodciubiow'}],
             'river': [{'action': 'CALL', 'amount': 0, 'paid': 0, 'uuid': 'zdmxlmfwytkigodciubiow'}]}
            
             }
"""


""" Example new_round_state modified by state class

        {
         'street': 'river', 'pot': {'main': {'amount': 400}, 'side': []},
         'community_card': ['DT', 'C2', 'ST', 'DA', 'HT'],
         'dealer_btn': 1, 'next_player': 1, 'small_blind_pos': 0, 'big_blind_pos': 1, 'round_count': 10,
         'small_blind_amount': 10,
         'seats': [{'name': 'f1', 'uuid': 'zdmxlmfwytkigodciubiow', 'stack': 10200, 'state': 'participating'},
                   {'name': 'FT2', 'uuid': 'lnjvmobrxhizukrppiqbda', 'stack': 9400, 'state': 'participating'}],
         'action_histories': {
             'preflop': [{'action': 'SMALLBLIND', 'amount': 10, 'add_amount': 10, 'uuid': 'zdmxlmfwytkigodciubiow'},
                         {'action': 'BIGBLIND', 'amount': 20, 'add_amount': 10, 'uuid': 'lnjvmobrxhizukrppiqbda'},
                         {'action': 'RAISE', 'amount': 40, 'paid': 30, 'add_amount': 20,
                          'uuid': 'zdmxlmfwytkigodciubiow'},
                         {'action': 'RAISE', 'amount': 60, 'paid': 40, 'add_amount': 20,
                          'uuid': 'lnjvmobrxhizukrppiqbda'},
                         {'action': 'RAISE', 'amount': 80, 'paid': 40, 'add_amount': 20,
                          'uuid': 'zdmxlmfwytkigodciubiow'},
                         {'action': 'CALL', 'amount': 80, 'paid': 20, 'uuid': 'lnjvmobrxhizukrppiqbda'}],
             'flop': [{'action': 'RAISE', 'amount': 20, 'paid': 20, 'add_amount': 20, 'uuid': 'zdmxlmfwytkigodciubiow'},
                      {'action': 'RAISE', 'amount': 40, 'paid': 40, 'add_amount': 20, 'uuid': 'lnjvmobrxhizukrppiqbda'},
                      {'action': 'RAISE', 'amount': 60, 'paid': 40, 'add_amount': 20, 'uuid': 'zdmxlmfwytkigodciubiow'},
                      {'action': 'RAISE', 'amount': 80, 'paid': 40, 'add_amount': 20, 'uuid': 'lnjvmobrxhizukrppiqbda'},
                      {'action': 'CALL', 'amount': 80, 'paid': 20, 'uuid': 'zdmxlmfwytkigodciubiow'}],
             'turn': [{'action': 'CALL', 'amount': 0, 'paid': 0, 'uuid': 'zdmxlmfwytkigodciubiow'},
                      {'action': 'RAISE', 'amount': 40, 'paid': 40, 'add_amount': 40, 'uuid': 'lnjvmobrxhizukrppiqbda'},
                      {'action': 'CALL', 'amount': 40, 'paid': 40, 'uuid': 'zdmxlmfwytkigodciubiow'}],
             'river': [{'action': 'CALL', 'amount': 0, 'paid': 0, 'uuid': 'zdmxlmfwytkigodciubiow'}]}

         'preflop_raises' : 2,
         'flop_raises' : 3,
         'turn_raises' : 2,
         'river_raises' : 2,
         'p0_raises' : 4,
         'p1_raises' : 5,
         'current_street_raises' : { 'river' : 2},
         'prev_history' : {'action': 'CALL', 'amount': 0, 'paid': 0, 'uuid': 'zdmxlmfwytkigodciubiow'},
         'p0_prev_amount' : 40,
         'p1_prev_amount' : 20
        }
"""

# TODO: check if showdown is a street
# TODO: use property getter/setter where applicable
class State:

    def __init__(self, round_state, hole_card_indices, community_card_indices, is_cached = False, is_terminal = False):
        self._round_state = round_state
        self.p0_uuid = round_state['seats'][0]['uuid']
        self.p1_uuid = round_state['seats'][1]['uuid']
        self.street = self._round_state['street']
        self.prev_history = ''
        self.is_cached = is_cached
        self.new_round_state = copy.deepcopy(self._round_state)
        self.hole_card_indices = hole_card_indices
        self.community_card_indices = community_card_indices
        
        self.round_num = {
            'preflop' : 0,
            'flop' : 1,
            'turn' : 2,
            'river' : 3
        }

        self.num_round = {
            0 : 'preflop',
            1 : 'flop',
            2 : 'turn',
            3 : 'river'
        }

        self.round_num_board_cards = {
            'preflop' : 0,
            'flop' : 3,
            'turn' : 4,
            'river' : 5
        }

        self.new_round_state['preflop_raises'] = 0
        self.new_round_state['flop_raises'] = 0
        self.new_round_state['turn_raises'] = 0
        self.new_round_state['river_raises'] = 0
        self.new_round_state['p0_raises'] = 0
        self.new_round_state['p1_raises'] = 0
        self.new_round_state['current_street_raises'] = {}
        self.new_round_state['prev_history'] = {}
        self.new_round_state['p0_prev_amount'] = 0
        self.new_round_state['p1_prev_amount'] = 0
        eventsorder= ['preflop', 'flop', 'turn', 'river','showdown']
        for street, street_history in sorted(round_state['action_histories'].items(), key = lambda i : eventsorder.index(i[0])):
            for ply in street_history:
                if ply['action'] == 'RAISE':
                    # Add raises to appropriate street
                    if street == 'preflop':
                        if 'preflop_raises' in self.new_round_state :
                            self.new_round_state['preflop_raises'] += 1
                        else :    
                            self.new_round_state['preflop_raises'] = 1
                    elif street == 'flop':
                        if 'flop_raises' in self.new_round_state :
                            self.new_round_state['flop_raises'] += 1
                        else :    
                            self.new_round_state['flop_raises'] = 1
                    elif street == 'turn':
                        if 'turn_raises' in self.new_round_state :
                            self.new_round_state['turn_raises'] += 1
                        else :    
                            self.new_round_state['turn_raises'] = 1
                    else:  # last street is river
                        if 'river_raises' in self.new_round_state :
                            self.new_round_state['river_raises'] += 1
                        else :    
                            self.new_round_state['river_raises'] = 1

                    # Add raises to appropriate player
                    if ply['uuid'] == self.p0_uuid:
                        if 'p0_raises' in self.new_round_state :
                            self.new_round_state['p0_raises'] += 1
                        else :    
                            self.new_round_state['p0_raises'] = 1
                        
                        # Add latest amount of p0 to p0_prev_amount
                        self.new_round_state['p0_prev_amount'] = ply['amount']
                    else:
                        if 'p1_raises' in self.new_round_state :
                            self.new_round_state['p1_raises'] += 1
                        else :    
                            self.new_round_state['p1_raises'] = 1

                        # Add latest amount of p1 to p1_prev_amount
                        self.new_round_state['p1_prev_amount'] = ply['amount']

                    # Increment current street raises
                    # If street is not in current_street_raises attribute, it means that the street has changed and must changed curr_street_raises accordingly
                    if 'current_street_raises' in self.new_round_state :
                        if street not in self.new_round_state['current_street_raises'] :
                            self.new_round_state['current_street_raises'] = {street : 1}
                        else :
                            self.new_round_state['current_street_raises'][street] += 1
                    else :
                        self.new_round_state['current_street_raises'] = {street : 1}

                self.new_round_state['prev_history'] = ply
                self.prev_history = ply

            
            # Need to account for when the street has changed but the action history in that street is still zero
            if 'current_street_raises' in self.new_round_state :
                if street not in self.new_round_state['current_street_raises'] and len(street_history) == 0 :
                    self.new_round_state['current_street_raises'] = {street : 0}
  

        self.prev_history = self._round_state['prev_history']
        self.current_player = self._round_state['next_player']
        self.p0_stack = self._round_state['seats'][0]['stack']
        self.p1_stack = round_state['seats'][1]['stack']
        self.is_terminal = is_terminal

    def get_num_hole_cards(self) :
        """Returns number of hole cards each player receives at the beginning of the game.
        
        Returns:
            int: Number of hole cards each player receives at the beginning of the game.
        """
        return len(self.hole_card_indices)

    def get_hole_card(self, card_index) :
        """Returns player's hole card
        Args:
            player_index (int): Index of the player.
            card_index (int): Index of the hole card.
        Returns:
            Hole card of given player on given index.
        Raises:
            ValueError: When card_index is greater or equal
                        to number of hole cards in the game.
        """
        return hole_card_indices[card_index]

    def get_round(self) :
        """Returns index of the current round of the game.
        Returns:
            int: Index of the current round of the game.
        """

        return self.round_num[self.street]

    def get_total_num_board_cards(self, round_index) :
        """Returns total number of board cards that are on the board in given round.
    
        Args:
            round_index (int): Index of the round
        Returns:
            int: Total number of board cards that are on the board in given round.
        Raises:
            ValueError: When round_index is greater or equal
                        to number of rounds in the game.
        """

        return self.round_num_board_cards[self.round_num[round_index]]

    def get_board_card(self, card_index) : 
        """Returns board card.
        Args:
            card_index (int): Index of the board card.
        Returns:
            Board card on given index.
        Raises:
            ValueError: When card_index is greater or equal
                        to number of board cards in current
                        round.
        """
        return community_card_indices[card_index]

    def get_action_type(self, round_index, action_index) : 
        """Returns type of action on given index taken in given round.
        Args:
            round_index (int): Index of the round.
            action_index (int): Index of the action.
        Returns:
            ActionType: Action type for given action in given round.
        Raises:
            ValueError: When round_index is greater or equal
                        to number of rounds in the game so far.
            ValueError: When action_index is greater or equal
                        to number of actions in given round.
        """

        action_histories = self.get_action_histories()
        street = self.num_round[round_index]
        street_action_history = action_histories[street]
        return street_action_history[action_index]

    def get_num_actions(self, round_index) :
        """Returns number of actions in given round.
        Args:
            round_index (int): Index of the round.
        Returns:
            int: Number of actions in given round.
        Raises:
            ValueError: When round_index is greater or equal
                        to number of rounds in the game so far.
        """
        
        action_histories = self.get_action_histories()
        street = self.num_round[round_index]
        street_action_history = action_histories[street]
        return len(street_action_history)

    def get_action_histories(self) :
        return self._round_state['action_histories']

    def get_new_round_state(self) :
        return self.new_round_state

    def get_preflop_raises (self) :
        return self.new_round_state['preflop_raises']

    def get_flop_raises (self) :
        return self.new_round_state['flop_raises']

    def get_turn_raises (self) :
        return self.new_round_state['turn_raises']

    def get_river_raises (self) :
        return self.new_round_state['river_raises']    

    def get_p0_raises (self) :
        return self.new_round_state['p0_raises']

    def get_p1_raises (self) :
        return self.new_round_state['p1_raises']   

    def get_current_street_raises (self) :
        return self.new_round_state['current_street_raises'][self.street]   

    def get_prev_history (self) :
        return self.new_round_state['prev_history']   

    def get_p0_prev_amount (self) :
        return self.new_round_state['p0_prev_amount']    

    def get_p1_prev_amount (self) :
        return self.new_round_state['p1_prev_amount']  

    def get_current_player (self) :
        return self.current_player

    def get_p0_stack (self) :
        return self.p0_stack

    def get_p1_stack (self) :
        return self.p1_stack   
    
    def get_main_pot(self) :
        return self.new_round_state['pot']['main']['amount']

    def get_side_pots(self) :
        return self.new_round_state['pot']['side']

    def current_player_uuid(self):
        return self.p0_uuid if self.current_player == 0 else self.p1_uuid

    def get_community_card_indices(self) :
        return self.community_card_indices

    def get_hole_card_indices(self) :
        return self.hole_card_indices    

    def get_is_cached_state(self) :
        return self.is_cached

